language: bash
services: docker
install:
  - docker build -t moodle-db-oracle-r2:11 .
script:
  - docker run --name test0 -p 1521:1521 -d moodle-db-oracle-r2:11
    - until docker logs test0 | grep -q 'Database opened.'; do echo 'Waiting for oracle to come up...' && sleep 15; done
    # Extremely nasty command to get the oracle version..
    # We have to work around the lack of piping/env variables..
    - >
        docker exec test0 bash -c "export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe;
        echo 'SELECT * FROM v\$version;' | /u01/app/oracle/product/11.2.0/xe/bin/sqlplus -S system/oracle@XE"
        | tee output.txt | grep CORE
after_failure:
    - cat output.txt
    - docker logs test0
after_script:
    - docker rm -f test0
