language: bash
services: docker
install:
  - docker build -t moodle-db-oracle-r2:latest .
script:
  - docker run --name test0 -p 1521:1521 -d moodle-db-oracle-r2:latest
  - until docker logs test0 | grep -q 'DATABASE IS READY TO USE!'; do echo 'Waiting for oracle to come up...' && sleep 15; done
  # Perfome some simple verifications:
  # - XE CDB exists.
  - >
      docker exec test0 /bin/bash -c "echo 'SELECT INSTANCE_NAME, VERSION  FROM V\$INSTANCE;' | sqlplus -s / as sysdba" |
      tee output.txt | grep XE | grep ' 21.'
after_failure:
  - cat output.txt
  - docker logs test0
after_script:
  - docker rm -f test0
